name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT 
        id: extract_branch

      - name: Use Go 1.13
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.13.x

      - uses: jaxxstorm/action-install-gh-release@v1.12.0 
        with:
          repo: tmedwards/tweego
          chmod: 0775
      - run : tweego source -o index.html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_branch: gh-pages
          publish_dir: ./
          destination_dir: ${{ steps.extract_branch.outputs.branch }}
