name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: build game
        run: |
          go install github.com/tmedwards/tweego@v2.0.0
          export PATH=$PATH:$(go env GOPATH)/bin
          tweego source -o dist/index.html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
