name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Go 1.13
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.13.x

      - uses: jaxxstorm/action-install-gh-release@v1.12.0 
        with:
          repo: tmedwards/tweego
          chmod: 0775

      - name: Build and deploy apps to gh-pages
        uses: Sauloxd/review-apps@v2.0.0
        with:
          branch: "gh-pages" # The branch you chose to be your github-pages source
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, if you want the apps URL commented in your PR
          apps: |
            {
              "branches": {
                "build": "tweego source -o index.html",
                "dist": "output/"
              }
            }
